*** Variables ***
${ADD TO CART BTN}             xpath://button[normalize-space()='ADD TO CART']
${Cart Icon}                   xpath://a[@class='cart-icon']
${PROCEED CHECKOUT BTN}        xpath://button[normalize-space()='PROCEED TO CHECKOUT']
${PLACE ORDER BTN}             xpath://button[normalize-space()='Place Order']
${SELECT_COUNTRY}              xpath://div[@class='wrapperTwo']//div
${IRAQ OPTION}                xpath://div[@class='wrapperTwo']//option[@value='Iraq']
${PROCEED BTN}                xpath://button[normalize-space()='Proceed']